spring:
  datasource:
    url: jdbc:mysql://112.74.16.186:3306/redis_test?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  application:
    name: redis-controller

  redis:
    host: localhost
    port: 6379
#    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.studyway.redis.test.entity


#logging:
#  config: log4j2-spring.xml
#  level:
#    cn.jay.repository: trace


